CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE artists (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  discogs_id INTEGER NOT NULL UNIQUE CHECK(discogs_id > 0),
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE releases (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  discogs_id INTEGER NOT NULL UNIQUE CHECK(discogs_id > 0),
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE artist_releases (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  artist_id INTEGER NOT NULL,
  release_id INTEGER NOT NULL,
  UNIQUE (artist_id, release_id) ON CONFLICT ABORT,
  FOREIGN KEY (artist_id) REFERENCES artists (id),
  FOREIGN KEY (release_id) REFERENCES releases (id)
);

CREATE TABLE records (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  release_id INTEGER NOT NULL,
  disc_number INTEGER NOT NULL CHECK (disc_number > 0),
  UNIQUE (release_id, disc_number) ON CONFLICT ABORT,
  FOREIGN KEY (release_id) REFERENCES releases (id)
);

